-- a. Excluindo todos os clientes que não compraram nada ainda;
DELETE FROM REQUEST
WHERE CDCUSTOMER IN (
    SELECT C.CDCUSTOMER 
    FROM CUSTOMER AS C
    LEFT JOIN REQUEST AS R ON R.CDCUSTOMER = C.CDCUSTOMER
    LEFT JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST = R.CDREQUEST 
    LEFT JOIN PRODUCT AS P ON PR.CDPRODUCT = P.CDPRODUCT 
    WHERE NMPRODUCT IS NULL
);

DELETE FROM CUSTOMER
WHERE CDCUSTOMER IN (
    SELECT C.CDCUSTOMER 
    FROM CUSTOMER AS C
    LEFT JOIN REQUEST AS R ON R.CDCUSTOMER = C.CDCUSTOMER
    LEFT JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST = R.CDREQUEST 
    LEFT JOIN PRODUCT AS P ON PR.CDPRODUCT = P.CDPRODUCT 
   WHERE NMPRODUCT IS NULL
);