-- b. Excluindo todos os fornecedores que não forneceram nenhum produto;
DELETE FROM SUPPLIER
WHERE CDSUPPLIER IN (
	SELECT SUPPLIER.CDSUPPLIER FROM PRODUCT RIGHT JOIN SUPPLIER ON
	PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER WHERE NMPRODUCT IS NULL
);