-- b. Excluindo todos os fornecedores que não forneceram nenhum produto;
DELETE FROM SUPPLIER
WHERE CDSUPPLIER IN (
	SELECT SUPPLIER.CDSUPPLIER 
	FROM PRODUCT AS P
	RIGHT JOIN SUPPLIER AS S ON P.CDSUPPLIER = S.CDSUPPLIER 
	WHERE NMPRODUCT IS NULL
);