-- c. Atualizando o valor de venda pelo preço original do produto;

UPDATE PRODUCTREQUEST SET PRODUCTREQUEST.VLUNITARY = PRODUCT.VLPRICE
FROM PRODUCTREQUEST JOIN PRODUCT 
ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
WHERE PRODUCTREQUEST.CDPRODUCT IS NOT NULL;