-- c. Atualizando o valor de venda pelo preço original do produto;

UPDATE PRODUCTREQUEST
SET PR.VLUNITARY = P.VLPRICE
FROM PRODUCTREQUEST AS PR 
JOIN PRODUCT AS P ON PR.CDPRODUCT = P.CDPRODUCT
WHERE PR.CDPRODUCT IS NOT NULL;