-- g. Faça o script que insira todos os produtos em todos os pedidos. Quantidade
-- 10 e preço original do produto.

INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT
    REQUEST.CDREQUEST,
    PRODUCT.CDPRODUCT,
    10,
    PRODUCT.VLPRICE
FROM
REQUEST,
PRODUCT
WHERE NOT EXISTS(
    SELECT 1
    FROM PRODUCTREQUEST 
    WHERE PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
    AND PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
);