-- . a. Todos os produtos comprados por cliente (nome), com o número de vezes que
-- foi comprado, a quantidade total comprada e o valor total já pago por aquele
-- produto;


SELECT NMCUSTOMER, NMPRODUCT, 
    COUNT(NMPRODUCT) AS 'TIMES BOUGHT', 
    COUNT(NMPRODUCT) * QTAMOUNT AS 'TOTAL AMOUNT', 
    COUNT(NMPRODUCT) * QTAMOUNT * VLUNITARY AS 'TOTAL SPENT' 
FROM PRODUCTREQUEST 
JOIN REQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST 
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER 
JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
 GROUP BY NMCUSTOMER, NMPRODUCT, QTAMOUNT, VLUNITARY