-- b. O número de pedidos e o total comprado por cliente (nome) no ano de 2003;

SELECT 
	NMCUSTOMER AS customer_name, 
	COUNT(*) AS total_bought, 
	SUM(QTAMOUNT*VLUNITARY) AS total_spent 
FROM PRODUCTREQUEST AS PR
JOIN REQUEST AS R ON PR.CDREQUEST = R.CDREQUEST 
JOIN CUSTOMER AS C ON C.CDCUSTOMER = R.CDCUSTOMER 
JOIN PRODUCT AS P ON PR.CDPRODUCT = P.CDPRODUCT
WHERE DTREQUEST 
BETWEEN 
	'2003-01-01' AND '2003-31-12'
GROUP BY NMCUSTOMER