-- b. O número de pedidos e o total comprado por cliente (nome) no ano de 2003;

SELECT NMCUSTOMER, 
	COUNT(*) AS 'TOTAL PRODUCTS BOUGHT IN 2003', 
	SUM(QTAMOUNT*VLUNITARY) AS 'TOTAL SPENT IN 2003' 
FROM PRODUCTREQUEST 
JOIN REQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST 
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER 
JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
WHERE DTREQUEST 
BETWEEN 
	'2003-01-01' AND '2003-31-12'
GROUP BY NMCUSTOMER