-- g. O nome do cliente, o nome do produto o nome do fornecedor, a data do
-- pedido, a data de entrega e o preço, somente se o fornecedor for de São Paulo
-- (011) e o preço seja maior que 20 reais

SELECT NMCUSTOMER, NMPRODUCT, NMSUPPLIER, DTREQUEST, DTDELIVER, VLTOTAL 
FROM CUSTOMER 
JOIN REQUEST ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT 
JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER 
WHERE SUPPLIER.IDFONE 
LIKE '(011)%' 
AND VLPRICE > 20;