-- d. O nome do cliente, o produto e o total que o cliente já gastou com esse
-- produto. Uma linha com o total por cliente e uma linha com o total geral;

SELECT 
    COALESCE(NMCUSTOMER, 'Total Geral'), 
    COALESCE(NMPRODUCT, 'Total'), 
    SUM(QTAMOUNT*VLUNITARY) 
FROM CUSTOMER 
JOIN REQUEST ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER 
JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST 
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY ROLLUP(NMCUSTOMER, NMPRODUCT)