-- g. O nome e o fornecedor do produto que já foi vendido mais que 3 vezes

SELECT NMPRODUCT, NMSUPPLIER 
FROM PRODUCT 
JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER 
JOIN PRODUCTREQUEST ON
PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
GROUP BY NMPRODUCT, NMSUPPLIER
HAVING COUNT(NMPRODUCT) > 3;