/* a. Faça os scripts para a criação das tabelas, sem as constraints; */

CREATE TABLE PRODUCTREQUEST(
	CDREQUEST INT,
	CDPRODUCT INT,
	QTAMOUNT INT,
	VLUNITARY MONEY
);

CREATE TABLE REQUEST (
	CDREQUEST INT,
	DTREQUEST DATETIME,
	CDCUSTOMER INT,
	VLTOTAL MONEY
);

CREATE TABLE CUSTOMER(
	CDCUSTOMER INT,
	NMCUSTOMER VARCHAR(250),
	NRFONE VARCHAR(50),
	DSADDRESS VARCHAR(250)
);

CREATE TABLE PRODUCT(
	CDPRODUCT INT,
	NMPRODUCT VARCHAR(250),
	CDSUPPLIER INT,
	VLPRICE MONEY,
	QTSTOCK INT
);

CREATE TABLE SUPPLIER (
	CDSUPPLIER INT,
	NMSUPPLIER VARCHAR(250),
	NRFONE VARCHAR(50)
);