/*b. Faça os scripts para a criação das chaves primárias das tabelas criadas;*/

/*Não é possível adicionar PK à uma coluna que não seja NOT NULL */
ALTER TABLE REQUEST
ALTER COLUMN CDREQUEST INT NOT NULL;

ALTER TABLE REQUEST 
ADD CONSTRAINT PK_CDREQUEST 
PRIMARY KEY(CDREQUEST);

ALTER TABLE CUSTOMER
ALTER COLUMN CDCUSTOMER INT NOT NULL;

ALTER TABLE CUSTOMER 
ADD CONSTRAINT PK_CDCUSTOMER
PRIMARY KEY(CDCUSTOMER);

ALTER TABLE PRODUCT
ALTER COLUMN CDPRODUCT INT NOT NULL;

ALTER TABLE PRODUCT
ADD CONSTRAINT PK_CDPRODUCT
PRIMARY KEY(CDPRODUCT);

ALTER TABLE SUPPLIER
ALTER COLUMN CDSUPPLIER INT NOT NULL;

ALTER TABLE SUPPLIER
ADD CONSTRAINT PK_CDSUPPLIER
PRIMARY KEY(CDSUPPLIER);
