-- a. O nome de todos os itens que já foram pedidos (fazer uma versão com
-- DISTINCT e uma com GROUP BY);

SELECT DISTINCT 
	NMPRODUCT AS product_name 
FROM PRODUCT AS P
JOIN PRODUCTREQUEST AS PR ON PR.CDPRODUCT = P.CDPRODUCT;

-- ou

SELECT 
	NMPRODUCT AS product_name
FROM PRODUCT AS P
JOIN PRODUCTREQUEST AS PR ON PR.CDPRODUCT = P.CDPRODUCT 
GROUP BY NMPRODUCT;