-- a. O nome de todos os itens que já foram pedidos (fazer uma versão com
-- DISTINCT e uma com GROUP BY);

SELECT DISTINCT NMPRODUCT 
FROM PRODUCT 
JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT;

-- ou

SELECT NMPRODUCT 
FROM PRODUCT 
JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT 
GROUP BY NMPRODUCT;