-- b. O nome do produto, o número de vezes que ele foi pedido e a quantidade total pedida;

SELECT NMPRODUCT, COUNT(*) AS 'VEZES QUE FOI PEDIDO', SUM(PRODUCTREQUEST.QTAMOUNT) AS 'QUANTIDADE TOTAL' 
FROM PRODUCT 
JOIN PRODUCTREQUEST ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT 
JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
GROUP BY NMPRODUCT;
