--e. A data do pedido, o nome do cliente, quantos produtos distintos ele pediu, o
--valor total do pedido (baseado nos valores da tabela productrequest), a média
--de valores do pedido (baseado nos valores da tabela productrequest)

SELECT DTREQUEST, NMCUSTOMER, COUNT(DISTINCT PRODUCT.CDPRODUCT) AS 'DISTINCT PRODUCTS', 
SUM(QTAMOUNT * VLUNITARY) AS 'TOTAL', AVG(QTAMOUNT * VLUNITARY) AS 'AVERAGE' 
FROM REQUEST 
JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER 
JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST 
JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
GROUP BY DTREQUEST, NMCUSTOMER
ORDER BY DTREQUEST;