--h. O nome do cliente, o produto, o valor gasto com o produto, quantas vezes ele
--foi pedido pelo cliente e o nome do fornecedor. Somente para produtos em
--que o cliente gastou mais de R$1.000,00, ordenado por cliente e produto.

SELECT NMCUSTOMER, NMPRODUCT, QTAMOUNT*VLUNITARY AS 'TOTAL SPENT', COUNT(NMPRODUCT), NMSUPPLIER 
FROM CUSTOMER 
JOIN REQUEST ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER 
JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT 
JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE QTAMOUNT*VLUNITARY > 1000
GROUP BY NMCUSTOMER, NMPRODUCT, QTAMOUNT, VLUNITARY, NMSUPPLIER
ORDER BY NMCUSTOMER, NMPRODUCT
